name: Generate stats card

on:
  schedule:
    # Executa a cada 12 horas
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate stats.svg
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: >
            username=${{ github.repository_owner }}
            &hide_title=false
            &hide_rank=false
            &show_icons=true
            &include_all_commits=true
            &count_private=true
            &disable_animations=false
            &theme=tokyonight
            &locale=pt-br
            &hide_border=true
          path: dist/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
